### ISSUE TITLE
Picker won't close when in modal

### ISSUE THREAD

**Issue by wimurk** [ibraheem-ghazi/four-boot#3]
### how to reproduce

I have a simple bootstrap modal. The content of the modal is loaded using jquery `$.get` inside that content there is a `select` with the class selectpicker.  My code below: 

```javascript
$(document).on('click', '.openTimer', function(e){
    e.stopPropagation();
    var token = $(this).data('token');
    $.post(openTimer, {_token:token, id:$(this).data('id')}, function(response){
        $('#timerModal').find('.modal-body').html(response);
        $('.selectpicker').fourBoot(); //here is the picker
        $("[data-toggle='switch']").bootstrapSwitch();
        $('#timerModal').modal('show');
    }).fail(function(){
        notify('danger', 'Something went wrong', 'nc-icon nc-simple-remove');
    });
});
```
It all loads fine till you select the picker. It wont close after that. 

![Look](https://i.gyazo.com/01a2d41713f05871096d2a558e6c65f6.gif)

**Comment by ibraheem-ghazi** [comment]
could you check if there is any error in console ?

**Comment by wimurk** [comment]
@IbraheemAlnabriss no errors are showen in the console
I had a similiar problem with summernote when i upgraded to bootstrap 4

**Comment by wimurk** [comment]
Any news on the fix?

**Comment by ibraheem-ghazi** [comment]
@wimurk, sorry i could regenerate your issue , i have copied and tested your code, and looks like it's working as expected, this issue might related to your code ,or usually it's a bootstrap 4 dropdown issue,
 just to ensure, have you loaded all requirements of JS for BS4 ?
could you please give a live example contains this issue ?
![image](https://user-images.githubusercontent.com/22643210/42648917-e04186f4-8610-11e8-871c-47db88477a7e.png)

**Comment by ibraheem-ghazi** [comment]
as there is no update on this issue by **wimurk** , 
and the issue was related to bootstrap issue 
i will close this issue.
thanks
