### ISSUE TITLE
Error on IE 11

### ISSUE THREAD

**Issue by mean-cj** [ibraheem-ghazi/four-boot#6]
Hello i found error on IE 11

SCRIPT1006: Expected ')'
JQuery.four-boot.js (127,39)

i think javascript could not define parameter
`function fourBoot(optionsOrMethod = null, paramsOrBag = null,param2=null) {`

i convert your code to ES2015 IE is not support includes
Object doesn't support property or method 'includes' 

Please check your project is not support IE
Thank you.

**Comment by ibraheem-ghazi** [comment]
thanks for reporting this important issue 
i have fixed this issue and the picker should work with IE11 (fix will be in the next version)
also soon i will release the next version of FourBoot
